version: '3'

services:
  web:
    image: nginx:1-alpine
    restart: always
    ports:
      - "80"
    networks:
      ingress:
        aliases:
         - backend-web
    volumes:
     - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
     - .:/var/www/html
  php:
    restart: always
    build:
      context: .
      dockerfile: docker/Dockerfile
    networks:
      ingress:
        aliases:
         - backend-php
    volumes:
     - .:/var/www/html

networks:
  ingress:
    external:
      name: ingress_default
